--AUTO_INCREMENT

DROP TABLE USERS;

CREATE TABLE USERS(
	user_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(128),
	email VARCHAR(128),
	PRIMARY KEY(user_id),
	INDEX (email)
);
-- MYSQL FUNCTIONS
-- INDEXES
HASHES OR TREES
-- MYSQL INDEX TYPES
PRIMARY KEY -- REQUIRES NO DUPLICATES
INDEX -- GOOD FOR INDIVIDUAL ROW LOOKUP AND SORTING 

--EXAMPLE 
--SPECIFYING INDEXES

ALTER TABLE USERS ADD INDEX (email) USING BTREE